// List of countries with their codes and flag emojis
export const countries = [
  { name: "Global", code: "GLO", flag: "🌍" },
  { name: "Kenya", code: "KE", flag: "🇰🇪" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦" },
  { name: "Ghana", code: "GH", flag: "🇬🇭" },
  { name: "Uganda", code: "UG", flag: "🇺🇬" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼" },
  { name: "Senegal", code: "SN", flag: "🇸🇳" },
  { name: "Mali", code: "ML", flag: "🇲🇱" },
  { name: "Ivory Coast", code: "CI", flag: "🇨🇮" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲" },
  { name: "South Sudan", code: "SS", flag: "🇸🇸" },
  { name: "United States", code: "US", flag: "🇺🇸" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "Canada", code: "CA", flag: "🇨🇦" },
  { name: "Australia", code: "AU", flag: "🇦🇺" },
  { name: "India", code: "IN", flag: "🇮🇳" },
  { name: "China", code: "CN", flag: "🇨🇳" },
  { name: "Japan", code: "JP", flag: "🇯🇵" },
  { name: "Brazil", code: "BR", flag: "🇧🇷" },
  { name: "Mexico", code: "MX", flag: "🇲🇽" },
  { name: "Egypt", code: "EG", flag: "🇪🇬" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲" },
  { name: "Malawi", code: "MW", flag: "🇲🇼" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿" }
];